### PR TITLE
Replace Cypress fork of actions/cache with official @actions/cache package

### PR DESCRIPTION
**Pull request by mondash**
### Linked issue
#61 

### Additional context
I haven't included any fix for the concurrency issue I mentioned in #61, but it looks like that issue stems from further upstream and isn't necessarily in the scope of this PR anyway. Nevertheless, I'll be keeping an eye on that issue (and maybe proposing a fix for it if I have the time) since it does affect me. If this PR is merged and that issue _does_ get resolved, I'd be happy to make another PR to introduce that fix into this action.

**Edit**: This PR _does_ now include a fix for the above mentioned issue

Feel free to hit me up if you have any questions or concerns. Thanks!

### Note
I ran `yarn upgrade` since I noticed a dependabot warning on my fork.
I have not updated the caching section of the README

### CODE REVIEW

**Comment by byCedric** [comment]
This looks great, thanks a lot! I'll test run this tomorrow too and fix the CI error. It basically says that the current build isn't up to date and needs to be rebuilt. 😄

**Comment by mondash** [comment]
Thanks for taking a quick interest in this. I really appreciate it!

Since I mentioned above (and so you don't need to go searching yourself), here's the stack of issues/PRs blocking the fix for the concurrency issue:

### The issue itself
"Cache already exists" due to concurrency: https://github.com/actions/toolkit/issues/537

### Needs to be merged before resolving the above issue
Throw HttpClientError instead of Error: https://github.com/actions/http-client/pull/32

### Causing tests to fail in above issue
/redirect-to returns 404: https://github.com/postmanlabs/httpbin/issues/617

**Comment by mondash** [comment]
@byCedric The PR resolving https://github.com/actions/toolkit/issues/537 was merged recently, so I took the liberty of adding the additional error handling to bring that fix into this repo.

**Comment by mondash** [comment]
@byCedric I don't want to rush you (especially if you have other priorities), but I did just want to bump this PR. Thanks again!

**Comment by byCedric** [comment]
Hey @mondash! I'm so sorry, you are right to ping me 🙈  We are working hard to push SDK 40 and some other cool stuff out the door. I'll get back to you asap!

**Comment by byCedric** [comment]
I'm so sorry for putting this off for so long! Thanks for your PR and persistence 🙈 . I'll tweak some small things, like logging with `core.info`, and will release asap after some testing! In the meantime, you can try your PR by using the `@master` branch.

**Comment by mondash** [comment]
@byCedric No worries, I know how schedules can be! :) Thanks _a lot_ for getting this through!

**Pull request merged**
