### PR TITLE
fix: update demo workflow to fix checkout issue

### PR DESCRIPTION
**Pull request by giautm**
### Linked issue
Fix the wrong commit issue with the solution from https://github.com/actions/checkout/issues/331#issuecomment-925405415

### CODE REVIEW

**Review by EvanBacon — APPROVED** [review]
lgtm, curious what @byCedric thinks

**Comment by byCedric** [comment]
Good catch, I think I found a couple of other issues too:

1. Looks like Github might have restricted the default github token even more. [When I run this as is, I get the `Error: Resource not accessible by integration` error](https://github.com/byCedric/expo-github-bot-test/actions/runs/2331308823). I think this happens when the bot wants to add the 👍 reaction. Should be fixable by adding:
    ```
    permissions:
      pull-requests: write
    ```
2. We aren't restricting the comments on pull requests only. Because `issue_comment` can be either a comment on an issue, or a comment on a pull, this causes the 1st issue but also opens the way for unexpected behavior (or unexpected action triggers, and thus wasting time) for non-pull comments. Should be fixable by adding:
    ```
    if: ${{ github.event.issue.pull_request }}
    ```

Then two minor things of which I'm not a super fan.

1. Checking out the main branch first, then the pull, kind of wastes a small amount of time. Would be nice if we could checkout the PR directly, e.g.
    ```
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
    ```
2. For every run, you'd have to create a new comment. It's a minor thing that mostly pops up during testing, but would be nice if we could also just "trigger on edits", so we can update the comment to re-trigger it. e.g.
    ```
    on:
      issue_comment:
        types: [created, edited]
    concurrency: 
      group: expo-bot-${{ github.event.issue.number }}
      cancel-in-progress: true
    ```

Then, some random thoughts to make feedback a bit more clear when running from actions (this might be irrelevant as soon as we move the bot to be a github app).

1. We could add a reaction with ⌛ in the [action's `pre` hook](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre). With this, we add feedback that the bot has started and is working it's way to perform the action we need.
2. We could add the 👍 or ❌ reactions in the [action's `post` hook](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost) whenever it failed or succeed. I think this might increase the feedback loop even more 😄

**Comment by byCedric** [comment]
To show an example that seems to work perfectly (including the listed 2 issues above):

```
name: Expo Comment Bot
on:
  # minor 2 - also trigger on updates and limit max concurrency
  issue_comment:
    types: [created, edited]
concurrency: 
  group: bot-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  bot:
    runs-on: ubuntu-latest
    # issue 2 - only trigger from comments on pulls
    if: ${{ github.event.issue.pull_request }}
    # issue 1 - allow the bot to comment on pulls
    permissions:
      pull-requests: write
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2
        with:
          # minor - 1 checkout the repo on the pull
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 📦 Install dependencies
        run: yarn install
      - name: 🤖 Run expo command
        uses: expo/expo-github-action/command@v7
```

**Comment by giautm** [comment]
> 1. We could add a reaction with ⌛ in the [action's pre hook](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre). With this, we add feedback that the bot has started and is working it's way to perform the action we need.
> 2. We could add the 👍 or ❌ reactions in the [action's post hook](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost) whenever it failed or succeed. I think this might increase the feedback loop even more 😄

I'm working on add check status for it

**Comment by giautm** [comment]
@EvanBacon, @byCedric: Can we merge this PR?

**Pull request merged**
